# This is a basic workflow to help you get started with Actions
name: upload to s3
# Controls when the action will run. 
on:
  # Triggers the workflow on push or pull request events but only for the main branch
  # push:
  #  branches: [ main ]
# Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:
# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
# This workflow contains a single job called "build"
  build:
# The type of runner that the job will run on
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@master
      - name: upload to s3
        run: |
          aws s3 cp updated-gluescript.py s3://big-data-project11/clean1/
        env:
          AWS_ACCESS_KEY_ID: ASIAUBM6XHT4JTAAXZ46
          AWS_SECRET_ACCESS_KEY: 9PatVK7osCP/OGaFuEf6dIzOlmclWZ9p2ohnjTK+
          AWS_DEFAULT_REGION: 'us-east-1'
          AWS_SESSION_TOKEN: FwoGZXIvYXdzEMz//////////wEaDJGzu5KMHEKWMy914SLJAZOh8ES5+IH/s3j1QTFB8GD5VhgCtqA+e485asdlfAX7b2tq1jd7yLLIFxpTThismebVtFeVxnEQYCyl6NMcMqxFlnTxT7lX7ELqfV/zqydwE9De7uKuSNao0dh+lpdbIOGJHDjxsffY+ZoByLCc2BZ1vLTNGj+fIakzsvLYgT4IvB55gUgmYEoSKpTQiVj0SwQ3MzQ4NVcqXmXJpWe22JCfzwr0We+UNZNt2nuOoXy/Q2qIQoTH6whPgjIyxurvF8EdhYAKc+ZbpCiMhKygBjIt2OKwtd4omovb0qsYSHLD3SRZBxrrqGXblCKXmjng6S2yUfyVlI63MfiSVoYN
      
      - uses: action/checkout@master
      - name: create glue job
        run:  |
          Description: AWS Glue Job using GitHub Script
          Resources:
            MyJob:
              Type: AWS::Glue::Job
              Properties:
                Command:
                  Name: glueetl
                  PythonVersion: 3
                  ScriptLocation: "s3://big-data-project11/clean1/updated-gluescript.py"
                Description: "This is a test job"
                Name: my-glue-job
                Role: "LabRole"
                DefaultArguments:
                  "--job-language": "python"
        env:
          AWS_ACCESS_KEY_ID: ASIAUBM6XHT4JTAAXZ46
          AWS_SECRET_ACCESS_KEY: 9PatVK7osCP/OGaFuEf6dIzOlmclWZ9p2ohnjTK+
          AWS_DEFAULT_REGION: 'us-east-1'
          AWS_SESSION_TOKEN: FwoGZXIvYXdzEMz//////////wEaDJGzu5KMHEKWMy914SLJAZOh8ES5+IH/s3j1QTFB8GD5VhgCtqA+e485asdlfAX7b2tq1jd7yLLIFxpTThismebVtFeVxnEQYCyl6NMcMqxFlnTxT7lX7ELqfV/zqydwE9De7uKuSNao0dh+lpdbIOGJHDjxsffY+ZoByLCc2BZ1vLTNGj+fIakzsvLYgT4IvB55gUgmYEoSKpTQiVj0SwQ3MzQ4NVcqXmXJpWe22JCfzwr0We+UNZNt2nuOoXy/Q2qIQoTH6whPgjIyxurvF8EdhYAKc+ZbpCiMhKygBjIt2OKwtd4omovb0qsYSHLD3SRZBxrrqGXblCKXmjng6S2yUfyVlI63MfiSVoYN

        


           
        
    


  



